### ISSUE TITLE
Fix interestPerSecondToRateUntilMaturity

### ISSUE THREAD

**Issue by elnilz** [fiatdao/sdk-i#28]
function is currently in fiat-ui-i utils but needs to be moved to sdk, see https://github.com/fiatdao/fiat-ui-i/issues/129

function should be updated according to specs here https://www.notion.so/fiatdao/Formulas-streamlined-30fe68af9da242b8bc88aa5e050dee1b#71e4d847ce9f4f85bf418dbbe8603e0d

also update function name to `interestPerSecondToInterestToMaturity` or simply `interestToMaturity`

**Comment by elnilz** [comment]
make sure to also implement/update the debtAtMaturity function and related code in the ui as suggested here https://github.com/fiatdao/sdk-i/issues/25

**Comment by SolcAndMe** [comment]
fixed in https://github.com/fiatdao/sdk-i/pull/34
