### ISSUE TITLE
Fix computeLeveredWithdrawal function

### ISSUE THREAD

**Issue by elnilz** [fiatdao/sdk-i#32]
combine lower and upper bound for `targetCollateralizationRatio` check as done here https://github.com/fiatdao/sdk-i/blob/7fdc4e04e917da596b1b7ad66c526dd979ed8be4/src/lever.js#L73

note that `maxCRForLeveredWithdrawal` function needs to be fixed first https://github.com/fiatdao/sdk-i/issues/31

**Comment by elnilz** [comment]
also remove this https://github.com/fiatdao/sdk-i/blob/7fdc4e04e917da596b1b7ad66c526dd979ed8be4/src/lever.js#L204

**Comment by SolcAndMe** [comment]
fixed in https://github.com/fiatdao/sdk-i/pull/34
