### ISSUE TITLE
Fix estimatedUnderlierForLeveredWithdrawal function

### ISSUE THREAD

**Issue by elnilz** [fiatdao/sdk-i#33]
specs https://www.notion.so/fiatdao/Formulas-streamlined-30fe68af9da242b8bc88aa5e050dee1b#44edc4ab9abb4ae799407667218a90e6

note that the delta is in which conversion rates are used, we need to work with `collateralToUnderlierRate` and `underlierToFiatRate` rates instead of the reverse rates (price impact is not symmetric but depends on swap direction)

so function args and how rates are applied changes as per the specs above

**Comment by SolcAndMe** [comment]
fixed in https://github.com/fiatdao/sdk-i/pull/34
